### ISSUE TITLE
Update highlight.js version to pickup release fixing memory leak

### ISSUE THREAD

**Issue by callie-openai** [wooorm/lowlight#60] opened 2024-09-30 16:50 UTC
https://github.com/highlightjs/highlight.js/blob/main/CHANGES.md#version-11110 was just released and the package.json for highlight won't pick up the minor version bump to `11.11.0`. Can we bump this (and potentially use `^11.11.0` so these can get picked up w/out re-release in the future?

Also happy to open a PR if that would help.

**Comment by wooorm** [comment] 2024-10-01 09:29
`^` doesn’t work well because we use the internals — that sometimes breaks.

@joshgoebel I am watching GH releases but hadn’t seen this one yet; perhaps you still meant to do that?

**Comment by wooorm** [comment] 2024-10-01 09:36
@callie-openai The version you refer to isn’t on npm yet. It is not released yet.

**Comment by callie-openai** [comment] 2024-10-01 16:56
@wooorm Sadly I realized that's correct, it is updated on the Changelog but not actually published yet. I'm not sure why, that seems unexpected. I'll keep monitoring and re-ping if I see it before you.

**Comment by urmauur** [comment] 2024-11-26 08:39
FYI, I saw this on 11.10.0: https://github.com/highlightjs/highlight.js/pull/4095. Should Lowlight update highlight.js to version 11.10.0? Here’s the comparison: https://github.com/highlightjs/highlight.js/compare/11.10.0…main.

**Comment by wooorm** [comment] 2024-11-26 09:49
Not sure what you are saying. It already is on 11.10 https://github.com/wooorm/lowlight/blob/main/package.json?

**Comment by wooorm** [comment] 2024-11-26 09:50
oh looks like that was never released

**Comment by wooorm** [comment] 2024-11-26 10:01
https://github.com/wooorm/lowlight/releases/tag/3.2.0 — could someone confirm if this issue is solved or can still be reproduced? Thanks

**Comment by wooorm** [comment] 2024-11-27 20:07
closing, I think this is solved

**Closed by wooorm** 2024-11-27 20:07 UTC
